### ISSUE TITLE
Possible enhancements for apartment maps

### ISSUE THREAD

**Issue by DarkenMoon** [lmj0011/courier-locker#1]
Hello, I have been using this app for about a month now and it has really helped in saving gate codes and making my own apartment maps.

There are a few features that I believe would be helpful in ensuring that the apartment map will take you to exactly where you need to go, and maintaining accuracy. 

1st would be either adding a way to toggle to satellite mode, or adding a way to make a point on the map based on coordinates (i believe that accessing Google Maps satellite data costs more.) 

2nd would be having a way to place your point on the map, and then an optional secondary point tied to the first point to be placed on the nearest road that allows you to access the building. I have found that sometimes Google maps will take you to the wrong road based on how the point is setup on the map.

**Comment by lmj0011** [comment]
>adding a way to toggle to satellite mode

>a way to place your point on the map, and then an optional secondary point tied to the first point to be placed on the nearest road that allows you to access the building

I didn't realized I had notifications turned off for my own repos, otherwise I would have responded to this sooner.

The satellite mode seems doable without extra cost [1][1], [2][2]

Looks like [polylines][3] will allow for creating paths from an accessible point (nearest road) to a building

I'm currently working on other improvements and features for this app. I will come back to this for further consideration.
In the meantime if you want early access to new features/improvements [sign up as a tester][4]

[1]: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#setMapStyle(com.google.android.gms.maps.model.MapStyleOptions)
[2]: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#setMapStyle(com.google.android.gms.maps.model.MapStyleOptions)
[3]: https://developers.google.com/maps/documentation/android-sdk/polygon-tutorial#add_a_polyline_to_draw_a_line_on_the_map
[4]: https://play.google.com/apps/testing/name.lmj0011.courierlocker.prod

**Comment by DarkenMoon** [comment]
I was always under the impression that it cost developers to access Google Maps data. Anywho, I have signed up to be a tester and will report any issues that I find on this Github. Thank you!

**Comment by lmj0011** [comment]
https://github.com/lmj0011/courier-locker/commit/b9895fa1219a9b9741f7632a3226a426fa2870fb

**Comment by lmj0011** [comment]
> 2nd would be having a way to place your point on the map, and then an optional secondary point tied to the first point to be placed on the nearest road that allows you to access the building. I have found that sometimes Google maps will take you to the wrong road based on how the point is setup on the map.

I just pushed `2.3.0-beta02`, which has this feature implemented, to the test track so you should be getting the update soon.


>optional secondary point tied to the first point

In the app it is referred to as a "waypoint" and shows up as an option when you tap a building marker on the map.

If this features helps you, would you be able to illustrate your use case here so I can use it in the documentation describing the feature?

@DarkenMoon

**Comment by DarkenMoon** [comment]
Awesome. I will test out the feature and let you know if there are any issues. This should help me with areas that don't have added roads yet. Thank you!
